[tool.poetry]
name = "oci-python-vanilla"
version = "0.1.0"
description = "OCI control scripts"
authors = ["ldraney"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
oci = "^2.159.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
